version: '3'

services:
  gitlab-runner:
    stdin_open: true
    tty: true
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8093:8093"
    volumes:
      - ./conf/:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
