version: '3'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
    # ping host.docker.internal to get ip; use ip to connect
    # direct connection to a seperate container works far more reliable
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgres/data

  webinterface:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@webinterface.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - 3050:80
