version: '3'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
    # ping host.docker.internal to get ip; use ip to connect
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgres/data
